### ISSUE TITLE
collectd: disable logging for locations with AirOS 6 snmp_profiles

### ISSUE THREAD

**Issue by FFHener** [freifunk-berlin/bbb-configs#766]
When a AirOS 6 AP has no Stations connected a snmp-call asking for their names results in a `NoSuchName` error for each parameter. That means a lot of log spamming. As we only need collectd logging when we debug it i would suggest adding a script at [rc.local](https://github.com/freifunk-berlin/bbb-configs/blob/master/roles/cfg_openwrt/templates/common/rc.local.j2) [deactivating logging](https://github.com/openwrt/packages/blob/75b72c402f714af08c18a635926b3210622de818/utils/collectd/files/collectd.init#L599) after boot.

**Comment by Noki** [comment]
> As we only need collectd logging when we debug it

I disagree. We want to have historical data for our sites so we can identify performance degradations. We have had antennas whose alignment has deteriorated over time, e.g. due to wind, snow load or unstable mounting, and we have had antennas that have deteriorated due to water ingress. We can only detect all of this with continuous monitoring.

**Comment by FFHener** [comment]
Thats a misunderstabding. Collectd should still log the snmp-data, but not the errors to logd locally on the device

**Comment by Noki** [comment]
Got it! Yes, that's what we want.
